version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      DB_URL: postgresql+psycopg://app:app@db:5432/app
    ports:
      - "8000:8000"
    depends_on:
      - db
